# Generated by Django 5.0.6 on 2026-06-10 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='death_date',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='father',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='spouse',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='familymember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='familytree.familymember'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='family/'),
        ),
    ]
