# Generated by Django 5.0.6 on 2026-06-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0002_alter_familymember_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='photo',
        ),
        migrations.AddField(
            model_name='familymember',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
