# Generated by Django 5.0.6 on 2026-06-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0003_remove_familymember_photo_familymember_death_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='death_date',
        ),
    ]
