# Generated by Django 5.0.6 on 2026-06-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0004_remove_familymember_death_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={},
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='parent',
        ),
        migrations.AddField(
            model_name='familymember',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
