# Generated by Django 5.0.6 on 2026-06-10 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0005_alter_familymember_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='parent_name',
        ),
        migrations.AddField(
            model_name='familymember',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='familytree.familymember'),
        ),
    ]
