# Generated by Django 5.0.6 on 2026-06-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0006_remove_familymember_parent_name_familymember_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
